create table if not exists site_profile (
  id bigint generated by default as identity primary key,
  brand_name text,
  hero_eyebrow text,
  hero_title text,
  hero_subtitle text,
  hero_body text,
  header_cta_label text,
  hero_primary_cta_label text,
  hero_primary_cta_href text,
  hero_secondary_cta_label text,
  hero_secondary_cta_href text,
  about_title text,
  about_skill_label text,
  about_skill_percent int,
  about_body text,
  about_card_title text,
  services_title text,
  portfolio_title text,
  testimonial_title text,
  contact_title text,
  contact_subtitle text,
  contact_primary_label text,
  contact_primary_href text,
  contact_secondary_label text,
  contact_secondary_href text,
  footer_copy text,
  hero_image_url text,
  about_image_url text
);

create table if not exists site_nav (
  id bigint generated by default as identity primary key,
  label text not null,
  href text not null,
  sort_order int default 100
);

create table if not exists site_socials (
  id bigint generated by default as identity primary key,
  label text not null,
  href text not null,
  icon_text text,
  sort_order int default 100
);

create table if not exists site_services (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  icon_text text,
  accent_color text,
  sort_order int default 100
);

create table if not exists site_projects (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  tag text,
  image_url text,
  sort_order int default 100
);

create table if not exists site_testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  body text,
  rating int default 5,
  image_url text,
  sort_order int default 100
);

create table if not exists site_downloads (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  file_url text,
  button_label text,
  sort_order int default 100
);
